---
title: 'RFC'
labels: ['draft']
body:
    - type: dropdown
      id: RFC_Type
      attributes:
          label: RFC TYpe
          description: Specify the target type of the RFC
          options:
              - Core hooks
              - Core API
              - UI component
              - Tool
      validations:
          required: true
    - type: input
      id: Contributors
      attributes:
          label: Contributors
          description: mention all contributors associated with the RFC.
      validations:
          required: true
    - type: textarea
      id: ContributorsX
      attributes:
          label: Contributors
          description: mention all contributors associated with the RFC.
          render: bash
      validations:
          required: true
    - type: markdown
      attributes:
          value: |
              ## Markdown header
              And some more markdown
    - type: input
      id: has-id
      attributes:
          label: Suggestions
          description: A description about suggestions to help you
      validations:
          required: true
    - type: dropdown
      id: download
      attributes:
          label: Which area of this project could be most improved?
          options:
              - Documentation
              - Pull request review time
              - Bug fix time
              - Release cadence
      validations:
          required: true
    - type: checkboxes
      attributes:
          label: Check that box!
          options:
              - label: This one!
                required: true
              - label: I won't stop you if you check this one, too
    - type: markdown
      attributes:
          value: |
              ### The thrilling conclusion
