---
title: 'RFC'
labels: ['rfc: draft']
body:
    - type: dropdown
      id: RFC_Type
      attributes:
          label: RFC Type
          description: Specify the target type of the RFC
          options:
              - Core hooks
              - Core API
              - UI component
              - Tool
              - Other
      validations:
          required: true
    - type: textarea
      id: Contributors
      attributes:
          label: Contributors
          description: Mention all contributors associated with the RFC.
      validations:
          required: true
    - type: textarea
      id: Description
      attributes:
          label: 📖 Description
          description: Provide a clear description of the component or feature and its general functionality.
          value: |
              1.
              2.
              3.
              ...
      validations:
          required: true

    - type: textarea
      id: Additional_Notes
      attributes:
          label: ✏️ Additional Notes
          description: All notes that help other contributors understand the reasons for adding, deleting, or changing a specific feature should be mentioned (like [Gemini Decision Records](https://avivgroup.atlassian.net/wiki/spaces/ADS/pages/533909731/GDR+Gemini+Decision+Records)).
      validations:
          required: false

    - type: textarea
      attributes:
          label: ✍️ Requirements
          description: |
                      - Clearly define the problem or need that the RFC aims to address.
                      - Clearly define the problem or need that the RFC aims to address.
                      - Ensure that the problem aligns with project goals and objectives. 
                      - Provide detailed design considerations for React components or features.
                      - Consider usability, accessibility, and responsiveness in the design.
    - type: checkboxes
      attributes:
          label: ♿️ Accessibility
          options:
              - label: nsure that the React components or features adhere to accessibility standards.
              - label: Research any pre-existing patterns and document the findings (e.g. https://www.w3.org/WAI/ARIA/apg/patterns/).
              - label: Ask the Accessibility Team (@gemini_accessibility) to get their advice.DD

    - type: markdown
      attributes:
          value: |
              ## 🎯Proposal
    - type: textarea
      attributes:
          label: 👪 Component Relation (Optional)
          description: Specify the React component's children relationship by adding a [Mermaid Diagram](https://mermaid.js.org/config/accessibility.html?#class-diagram) and Consider the reusability and maintainability aspects of React components.
          value: |
              1.
              2.
              3.
              ...
    - type: checkboxes
      attributes:
          label: 👨🏻‍💻 Types & Usage
          options:
              - label: Determine the approach for types and state management (e.g., local state, Context API).
              - label: Consider how state changes will be handled and communicated.
              - label: Provide a rudimentary example of how your feature would be used.

    - type: textarea
      id: Clarifications
      attributes:
          label: ❓ Clarifications (Optional)
          description: Add all questions, open decisions or inquiries that need an answer or clarification from other contributors.
          value: |
              1.
              2.
              3.
              ...
      validations:
          required: false
    - type: checkboxes
      attributes:
          label: 🔗 Related Links, add all relevant links such as
          options:
              - label: Jira ticket
              - label: Figma design
              - label: add [Gemini Decision Record](https://avivgroup.atlassian.net/wiki/spaces/ADS/pages/533909731/GDR+Gemini+Decision+Records)
              - label: Research links
              - label: Related Pull Requests
